version: '3'

services:
    localstack:
        image: localstack/localstack
        ports:
            - "4566-4599:4566-4599"
            - "${PORT_WEB_UI-9000}:${PORT_WEB_UI-9000}"
        environment:
            - SERVICES=s3
            - PORT_WEB_UI=9000
            - AWS_ACCESS_KEY_ID=AXXXXXXXXXXXXE
            - AWS_SECRET_ACCESS_KEY=wXXXXXXXXXXXXY
            - AWS_DEFAULT_REGION=us-west-2