java:
    runtime:
        version: 8
spring:
    kafka:
        bootstrap-servers: kafka:9092
kafka:
    bootstrapAddress: kafka:9092
localstack:
    enabled: true
    s3:
        bucketName: test
        enabled: true
    services: S3
    sqs:
        enabled: false
server:
    port: 8081
