java:
    runtime:
        version: 11
kafka:
    bootstrapAddress: localhost:9092
localstack:
    enabled: true
    s3:
        bucketName: test
        enabled: true
    services: S3
    sqs:
        enabled: false
server:
    port: 8081
